### PR TITLE
118-add-argument-to-specify-run-directory-in-pm_fit

### LINKED ISSUE #118: Add argument to specify run directory in PM_fit
A great advantage with Pmetrics 2.0 and R6 is that you can specify both datasets and models in R, and thus don't have to rely on copying files. However, whenever `PM_fit$run()` is called, it uses the current working directory.

I suggest an argument in `PM_fit$run()`, e.g. `rundir`, that would take a path as input, and temporarily change the working directory to that directory, before starting the run. If no path is provided, it should use the current working directory.

### PR DESCRIPTION
**Pull request by Siel**
Closes #118

### CODE REVIEW

**Comment by mhovd** [comment]
Tested on Windows 10, R 4.1.3. Worked as expected!
I made a PR with an error check, because when specifying a directory that doesn't exist it would throw an uninformative error.

**Comment by Siel** [comment]
Thanks @mhovd. It is Thanksgiving today, so professor @mnneely is busy. let's wait for the weekend to merge it.

**Comment by Siel** [comment]
@mhovd What do you think about creating the folder if it does not exists?

**Comment by mhovd** [comment]
> @mhovd What do you think about creating the folder if it does not exists?

I would prefer if that wasn't the case, as creating it beforehand would require taking a stance on where it should be run.

**Comment by mnneely** [comment]
Approved

**Pull request merged**
