### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by Siel**
This is a initial version of plot.PMcycle, all the plots are implemented but there are some corner-case scenarios that are not. The idea is to find them and clean up the code before merging.

Command to install this branch:

`devtools::install_github("LAPKB/Pmetrics", ref = "Plotting")`

Please refer all improvements to the Plotting branch

### CODE REVIEW

**Comment by Siel** [comment]
This is before:
Rplot01

And this is after
Rplot

Any suggestion in the matter to make them prettier will be highly appreciated

**Comment by dadragon321** [comment]
I'll get right on that, sorry I had some things come up that had to be
dealt with last week.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Siel** [comment]
@mnneely All the plot functionalities of plot.PMcov are also implemented in this branch.

So, right now we have PMcycle and PMcov, should we merge with master? or wait for the other plots?

**Comment by Siel** [comment]
This is an example of plot.PMCov 
image

**Comment by mnneely** [comment]
Go ahead and merge.

**Comment by mnneely** [comment]
Merging at your request.  Plots are looking good!

**Pull request merged**
