### PR TITLE
Syntaxcheck fix unix

### LINKED ISSUE #6: When using ifort on unix, correct syntax for syntax-only
According to :
https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-syntax-only
Linux and macOS:  -syntax-only
Windows: | /syntax-only

In the R file: PMutilities.R
The Windows version is included and this make it fail on Centos6.8
if (length(grep("ifort", fortran) > 0)) { syntaxcheck <- paste(fortran, "/syntax-only", modelFor) }

So I sugest:
 if (length(grep("ifort", fortran) > 0)) {
    if (OS == 1 | OS == 3) {
      syntaxcheck <- paste(fortran, "-fsyntax-only", modelFor)
    } else {
      syntaxcheck <- paste(fortran, "/syntax-only", modelFor)
    }
  }

### PR DESCRIPTION
**Pull request by Sabryr**
This pull request is to elaborate issue #6 not necessarily to be integrated. Of cause if this is the fix please do merge it otherwise provide an alternative solution.

### CODE REVIEW

**Comment by Siel** [comment]
@masyamada Can you check this? thanks!

**Comment by masyamada** [comment]
This looks OK - I think it's OK to merge this pull request.

**Comment by Siel** [comment]
This Change will be released on v1.9.4. @mnneely it is ok to merge.
@Sabryr Thanks!

**Comment by mnneely** [comment]
Merged per instructions.

**Pull request merged**
