### PR TITLE
Model library in R

### LINKED ISSUE #120: Model library in R
Several models are available in the LAPK [model library](http://www.lapk.org/ModelLib.php).
Would it be possible to have these available in R?
I suggest a library function, e.g. `modelLibrary`, which takes an argument specifying the desired model.
This would further simply the workflow once a dataset has been imported in to R, and I image one could be able to then use
```
mod = PM_model$new(modelLibrary("1comp"))
```
If needed, one can then (as usual) update the model with `mod$update()`.

Would this be feasible?

### PR DESCRIPTION
**Pull request by Siel**
Created a new exported stucture called modelLibrary, it is a lisk that contains some model examples.

This is my proposal of implementation to close #120.

Example of use:

```
#To access all examples in the library:
library(Pmetrics)
names(modelLibrary)

To create a new model

model <- PM_model$new(modelLibrary$mod_2C_D)
```

Note: The names I'm using in that structure are the ones on the actual [Model Library](http://www.lapk.org/ModelLib.php). But I think we should change them to something more meaningful.

What you think?

>

### CODE REVIEW

**Comment by mhovd** [comment]
I think your proposed implementation looks good!
The models themselves can be further described in documentation, through `?modelLibrary`.
Perhaps `modelLibrary` should be a function, so that it can be better documented?
That way one could supply e.g. `modelLibrary(model = "list")` as an argument to list all the available models in the library, each with a brief description, while `modelLibrary(model = "2C_D")` (model name to be improved) would output the model object. 

As for the naming, something illustrative would be `n_compx`, where n is the number of compartments, and x is a running number for each model with that many compartments?

**Comment by mhovd** [comment]
Actually, I just found out that exported structures can be documented just as well as functions, so for the sake of simplicity maybe it should remain a list?

**Comment by Siel** [comment]
I like the list because the autocompleme functionality can help the users to see which options they have at their disposal. Let's wait for some input from professor Neely.

**Comment by mhovd** [comment]
The standard error model for the models in the library is
```
#Err
L=0.1
0.1,0.1,0,0
```

This is fine, except for the low value of L, which I think should have a default value of at least 5, or even 10. With a less restrictive error model, the library will have a lower change of resulting in a probability error for most data.

**Comment by CRquantum** [comment]
Can you send some model and data csv files that produce the probability error you mentioned? I would like to investigate it and possibly fix the issue. Thanks.

Also, do you have some model and data csv files that can reproduce the so called “Hessian” error which crashes Pmetrics? Thanks. I think I have fixed this issue, but I need more model and data csv to test. Once confirmed the issue is fixed, we should be able to release the fixed version.

On Dec 5, 2022, at 06:29, Markus ***@***.***> wrote:

﻿

The standard error model for the models in the library is

#Err
L=0.1
0.1,0.1,0,0


This is fine, except for the low value of L, which I think should have a default value of at least 5, or even 10. With a less restrictive error model, the library will have a lower change of resulting in a probability error for most data.

**Comment by mhovd** [comment]
> Can you send some model and data csv files that produce the probability error you mentioned? I would like to investigate it and possibly fix the issue.

This can be reproduced using the built-in model and data provided in `NPex`, and setting `G = 0.01` in the model. As expected, Pmetrics will incur an error, stating (correctly) that the probability of the observed data (for one or more individuals) given the current model is zero.

> Also, do you have some model and data csv files that can reproduce the so called “Hessian” error which crashes Pmetrics? 

Sure, I should have several examples. I will try to reduce the model and data to a minimal example, and will send you the files by e-mail when I find the time. Thank you!

**Comment by Siel** [comment]
> The standard error model for the models in the library is
> 
> ```
> #Err
> L=0.1
> 0.1,0.1,0,0
> ```
> 
> This is fine, except for the low value of L, which I think should have a default value of at least 5, or even 10. With a less restrictive error model, the library will have a lower change of resulting in a probability error for most data.

I Agree, we should define a higher default. we can start with 5.

I'll finish translating the other models and look into how to handle the documentation.

Thanks Markus

**Pull request merged**
