### PR TITLE
Declare necessary imports for `PM_report`

### LINKED ISSUE #187: Namespace is incomplete
New users downloading the latest of version of Pmetrics will encounter the following error when running PM_load()` for the first time

```
Use PM_load() to load them.

The following objects have been saved:

NPdata: All output from NPAG
[Some lines omitted for brevity]
Generating report based on the plotly template...

Quitting from lines 8-11 [unnamed-chunk-28] (plotly.Rmd)

Quitting from lines 8-11 (plotly.Rmd)
Error in `loadNamespace()`:
! there is no package called 'DT'
```

We need to make sure that all packages used in the report templates are declared in the `NAMESPACE`, so all dependencies are installed accordingly.

### PR DESCRIPTION
**Pull request by mhovd**
Fixes #187

### CODE REVIEW

**Comment by Siel** [comment]
This PR has to be approved by @mnneely because he was actually trying to reduce the size of the NAMESPACE

**Comment by mhovd** [comment]
> This PR has to be approved by @mnneely because he was actually trying to reduce the size of the NAMESPACE

Let me know if you want any assistance on this, I'd be happy to help! Still, as this is a breaking bug, I think the package would benefit from a merge, followed by namespace cleaning.

**Comment by mnneely** [comment]
Hi guys, happy new year! It says merging is blocked due to a failure of pkgdown. Do you want me to overrride and approve the pull request?


______________________________________

Michael Neely, MD, MSc, FCP | Chief, Division of Infectious Diseases

Director, Laboratory of Applied Pharmacokinetics and Bioinformatics (www.lapk.org<http://www.lapk.org/>),
The Saban Research Institute,
Children's Hospital Los Angeles

4650 Sunset. Blvd, #MS 176 | Los Angeles, CA 90027
Ph: 323.361.5047 | Fax: 323.361.1183 | ***@***.******@***.***>

www.chla.org<http://www.chla.org/>

Professor and Clinical Scholar | Department of Pediatrics,

Keck School of Medicine | University of Southern California
www.usc.edu<http://www.usc.edu/>

________________________________

**Comment by mhovd** [comment]
> Hi guys, happy new year! It says merging is blocked due to a failure of pkgdown. Do you want me to overrride and approve the pull request?

Happy new year!
That would be great, as the `pgkdown` build error appears to be due to an issue with GitHub, and not the code per se.

**Review by Siel — APPROVED** [review]

**Pull request merged**
